### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'locals' (new in 1.3.0)

### ISSUE THREAD

**Issue by pylint-bot** [pylint-dev/astroid#57]
Originally reported by: **Jace Browning (BitBucket: [jacebrowning](http://bitbucket.org/jacebrowning), GitHub: @jacebrowning?)**

---

I just started getting this crash after updating asteroid to 1.3.0 from 1.2.1:

```
#!shell

pylint yorm --rcfile=.pylintrc
Traceback (most recent call last):
  File "env/bin/pylint", line 9, in <module>
    load_entry_point('pylint==1.3.1', 'console_scripts', 'pylint')()
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/__init__.py", line 21, in run_pylint
    Run(sys.argv[1:])
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/lint.py", line 991, in __init__
    linter.check(args)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/lint.py", line 585, in check
    self.check_astroid_module(astroid, walker, rawcheckers, tokencheckers)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/lint.py", line 662, in check_astroid_module
    walker.walk(astroid)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/utils.py", line 804, in walk
    self.walk(child)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/utils.py", line 801, in walk
    cb(astroid)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/pylint/checkers/variables.py", line 756, in visit_import
    module = next(node.infer_name_module(parts[0]))
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/bases.py", line 110, in cache_generator
    for result in generator:
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/bases.py", line 341, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/inference.py", line 212, in infer_import
    yield self.do_import_module(lookupname)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/mixins.py", line 107, in do_import_module
    return mymodule.import_module(modname, level=level)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/scoped_nodes.py", line 361, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/manager.py", line 147, in ast_from_module_name
    return self.ast_from_file(filepath, modname, fallback=False)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/manager.py", line 109, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/rebuilder.py", line 148, in visit_module
    return self._transform(newnode)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/manager.py", line 324, in transform
    ret = transform_func(node)
  File "/Users/Browning/Programs/YORM/env/lib/python3.4/site-packages/astroid/__init__.py", line 115, in transform
    for name, obj in extension_module.locals.items():
AttributeError: 'NoneType' object has no attribute 'locals'
```

---
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/57
